import images from '../../assets/images';

export const butcherLocations = [
  'Dhanmondi, Dhaka',
  'Gulshan, Dhaka',
  'Mirpur, Dhaka',
  'Uttara, Dhaka',
  'Mohammadpur, Dhaka',
  'Banani, Dhaka',
  'Chattogram',
];

export const butcherAnimals = ['Cow', 'Goat', 'Sheep', 'Camel', 'Shared Cow'];

export const butcherServices = [
  'Slaughter & cutting',
  'Cutting & packaging',
  'Shared cow service',
];

export const butchers = [
  {
    id: 'rashid-ali',
    name: 'Rashid Ali',
    initials: 'RA',
    image: images.RA,
    area: 'Dhanmondi, Dhaka',
    rating: 4.9,
    reviews: 342,
    experience: 8,
    animals: ['Cow', 'Goat', 'Sheep', 'Camel'],
    services: ['Slaughter & cutting', 'Cutting & packaging'],
    startingPrice: 3500,
    availability: 'Available',
    completedServices: 342,
    verified: true,
    recommended: true,
  },
  {
    id: 'kamran-sheikh',
    name: 'Kamran Sheikh',
    initials: 'KS',
    image: images.KS,
    area: 'Gulshan, Dhaka',
    rating: 4.8,
    reviews: 298,
    experience: 11,
    animals: ['Goat', 'Sheep', 'Cow'],
    services: ['Slaughter & cutting', 'Cutting & packaging'],
    startingPrice: 4200,
    availability: 'Limited slots',
    completedServices: 298,
    verified: true,
    recommended: true,
  },
  {
    id: 'imran-hossain',
    name: 'Imran Hossain',
    initials: 'IH',
    image: images.IH,
    area: 'Mirpur, Dhaka',
    rating: 4.8,
    reviews: 275,
    experience: 7,
    animals: ['Shared Cow', 'Cow', 'Goat'],
    services: ['Shared cow service', 'Slaughter & cutting'],
    startingPrice: 2900,
    availability: 'Available',
    completedServices: 275,
    verified: true,
    recommended: true,
  },
  {
    id: 'abdul-karim',
    name: 'Abdul Karim',
    initials: 'AK',
    area: 'Uttara, Dhaka',
    rating: 4.7,
    reviews: 214,
    experience: 9,
    animals: ['Cow', 'Goat', 'Camel'],
    services: ['Slaughter & cutting', 'Cutting & packaging'],
    startingPrice: 3800,
    availability: 'Available',
    completedServices: 231,
    verified: true,
    recommended: false,
  },
  {
    id: 'shafiq-uddin',
    name: 'Shafiq Uddin',
    initials: 'SU',
    area: 'Mohammadpur, Dhaka',
    rating: 4.6,
    reviews: 186,
    experience: 6,
    animals: ['Goat', 'Sheep'],
    services: ['Slaughter & cutting', 'Cutting & packaging'],
    startingPrice: 2500,
    availability: 'Limited slots',
    completedServices: 194,
    verified: true,
    recommended: false,
  },
  {
    id: 'mizanur-rahman',
    name: 'Mizanur Rahman',
    initials: 'MR',
    area: 'Banani, Dhaka',
    rating: 4.5,
    reviews: 153,
    experience: 5,
    animals: ['Cow', 'Goat', 'Sheep'],
    services: ['Slaughter & cutting', 'Shared cow service'],
    startingPrice: 3200,
    availability: 'Unavailable',
    completedServices: 167,
    verified: true,
    recommended: false,
  },
  {
    id: 'tariqul-islam',
    name: 'Tariqul Islam',
    initials: 'TI',
    area: 'Chattogram',
    rating: 4.4,
    reviews: 89,
    experience: 4,
    animals: ['Cow', 'Goat'],
    services: ['Slaughter & cutting'],
    startingPrice: 2800,
    availability: 'Available',
    completedServices: 96,
    verified: false,
    recommended: false,
  },
];
